# Uncomment this line to define a global platform for your project
platform :ios, ‘8.1’
# Uncomment this line if you're using Swift
use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

target 'Google Map project' do
	pod 'GoogleMaps'
end

